// <auto-generated />
using System;
using BoardingHouse.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardingHouse.DAL.Migrations
{
    [DbContext(typeof(BoardingHouseContext))]
    partial class BoardingHouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoardingHouse.DAL.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("ID");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.ChiTietKhachO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaKhach")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaKhach");

                    b.ToTable("ChiTietKhachO");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienMang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaPhong");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<bool>("DaKetThuc")
                        .HasColumnType("bit");

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaKhach")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaKhach");

                    b.HasIndex("MaPhong");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKhach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhach"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKhach");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.NguoiDung", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserName");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoai");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.SoDienNuoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChiSoDienCu")
                        .HasColumnType("int");

                    b.Property<int>("ChiSoDienMoi")
                        .HasColumnType("int");

                    b.Property<int>("ChiSoNuocCu")
                        .HasColumnType("int");

                    b.Property<int>("ChiSoNuocMoi")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaPhong");

                    b.ToTable("SoDienNuoc");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.ThamSo", b =>
                {
                    b.Property<string>("TenThamSo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenThamSo");

                    b.ToTable("ThamSo");

                    b.HasData(
                        new
                        {
                            TenThamSo = "GIA_DIEN",
                            GiaTri = 3500m,
                            MoTa = "Giá điện (đ/kwh)"
                        },
                        new
                        {
                            TenThamSo = "GIA_NUOC",
                            GiaTri = 15000m,
                            MoTa = "Giá nước (đ/m3)"
                        },
                        new
                        {
                            TenThamSo = "GIA_DICH_VU",
                            GiaTri = 100000m,
                            MoTa = "Dịch vụ chung (Rác, vệ sinh)"
                        },
                        new
                        {
                            TenThamSo = "GIA_MANG",
                            GiaTri = 50000m,
                            MoTa = "Tiền Wifi/Internet"
                        });
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("BoardingHouse.DAL.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.ChiTietKhachO", b =>
                {
                    b.HasOne("BoardingHouse.DAL.Entities.HopDong", "HopDong")
                        .WithMany("ChiTietKhachOs")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardingHouse.DAL.Entities.KhachHang", "KhachHang")
                        .WithMany("ChiTietKhachOs")
                        .HasForeignKey("MaKhach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.HoaDon", b =>
                {
                    b.HasOne("BoardingHouse.DAL.Entities.Phong", "Phong")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.HopDong", b =>
                {
                    b.HasOne("BoardingHouse.DAL.Entities.KhachHang", "KhachHang")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaKhach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoardingHouse.DAL.Entities.Phong", "Phong")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.Phong", b =>
                {
                    b.HasOne("BoardingHouse.DAL.Entities.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.SoDienNuoc", b =>
                {
                    b.HasOne("BoardingHouse.DAL.Entities.Phong", "Phong")
                        .WithMany("SoDienNuocs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.HopDong", b =>
                {
                    b.Navigation("ChiTietKhachOs");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("ChiTietKhachOs");

                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("BoardingHouse.DAL.Entities.Phong", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("HopDongs");

                    b.Navigation("SoDienNuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
